name: Format Code with Black

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  
jobs:
  format-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.18"

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black . --line-length 120

      - name: Commit formatted code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git commit -am "Chore: [auto] Black'd"; then
            if git push; then
              echo "Pushed changes"
            else
              echo "Creating a PR because push failed"
              git checkout -B black
              git push --set-upstream origin black
              gh pr create -B master -H black --title "Chore: Manually ran auto black" --body 'Created by Github action'
              echo "PR made to master"
            fi
          else
            echo "No changes"
          fi