name: Pytest

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.18'
        architecture: 'x64'

    - name: Restore cached wheels
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip/wheels # Or the directory where your wheels are built
        key: wheels-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/setup.py') }} # Adjust dependency file as needed
        restore-keys: |
          wheels-${{ runner.os }}-

    # Install runtime dependencies and the package itself
    - name: Install package and dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential
        python -m pip install --upgrade pip
        pip install -e .[test]

    # Install testing dependencies from pyproject.toml
    - name: Install test dependencies
      run: |
        python -m pip install pytest pytest-cov

    - name: Save wheels to cache
      if: success() # Only save if the build was successful
      uses: actions/cache/save@v4
      with:
        path: ~/.cache/pip/wheels # Or the directory where your wheels are built
        key: wheels-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/setup.py') }}

    # Run tests with coverage
    - name: Run tests and check coverage
      run: |
        pytest --cov=build_the_bot --cov-report=term-missing --cov-fail-under=100

